FROM python:3.9.0

WORKDIR /home/

RUN git clone https://github.com/SYkeem/pragmatic.git

WORKDIR /home/pragmatic/

RUN pip install -r requirements.txt

RUN echo "SECRET_KEY=django-insecure-3q8^u^92#%p&#5f7ex&!k-#+(v#=ltxu1ieeywy^45cf(6k668" > .env

RUN python manage.py migrate

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
